### ISSUE TITLE
Ajout d'un filtre sur le champ "output"

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-service-monitoring#18]
---

Author Name: **Jeremy CLAUSS** (Jeremy CLAUSS)
Original Redmine Issue: 6349, https://forge.centreon.com/issues/6349
Original Date: 2015-04-20

---

Bonjour,

serait-il possible d'ajouter un champ dans les paramètres du widget Service Monitoring afin de filtrer sur le champ "s.output", et ce, sur plusieurs valeurs ?

Cela permettrait de dire : ne pas afficher le service si la sortie contient "Process Timeout" ou "NRPE Timeout" par exemple.

Merci.

Jérémy.

**Comment by thoms27** [comment]
Bonjour,

Pouvez vous me dire à quoi correspond la sortie Process TImeout ? Est ce le plugin qui ne renvoie rien ? ou l'équipement interrogé qui ne renvoie rien ?

Je vous demande cela car j'ai beaucoup de message de ce type et je voulais savoir si le problème était local à la sup ou au réseau.

Merci d'avance.

**Comment by julienmathis** [comment]
Bonjour, 

Cela veut dire que le plugin est trop long a s'exécuter. tu peux régler dans centengine.cfg le service timeout afin de pouvoir bénéficier de temps plus long pour l'exécution des plugins. Mais le mieux est de corriger le plugin pour qu'il soit plus rapide.

Cordialement,
