### ISSUE TITLE
Ability to use multiple service / hosts filters on widgets

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-service-monitoring#19]
---

Author Name: **Eduardo Bayon Perales** (Eduardo Bayon Perales)
Original Redmine Issue: 4509, https://forge.centreon.com/issues/4509
Original Date: 2013-05-31

---

Hi everyone. I'm excited on the capabilities introduced on centreon 2.4 (I was on 2.3.9) and I like very much "Custom Views". I have one idea I think useful: 
In widgets we have the ability of adding only one filter on every item (i.e. One filter for service description, as "NOT LIKE" %disk usage%). I think it would be very useful to be able to use multiple filters, at least, to be able to use MySQL language to use this capability.
One example: It would be fantastic to be able to exclude from my services widget those related to disk usage and cpu usage, so in a text field I would be able to write down: "NOT LIKE '%disk usage%' AND NOT LIKE '%cpu usage%'"
I understand it would be very complicated to be able to offer multiple filters on a simple UI, but to be able to choose between simple filters and advanced filters to people knowing about MySQL language it's very useful, at least for me. 
Thanks in advance

**Comment by duy-31** [comment]
bonjour, j ai trouvé une solution et posté la procédure sur le forum.

https://forum.centreon.com/forum/centreon-ui/centreon-web-interface/140450-centreon-2-7-widget-service-monitoring-multiple-filter
