### ISSUE TITLE
Patch to add Latency and execution time in service-monitoring widget

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-service-monitoring#22]
---

Author Name: **charles judith** (charles judith)
Original Redmine Issue: 4615, https://forge.centreon.com/issues/4615
Original Date: 2013-07-09

---

Hi,

Patches in attachment for adding latency and execution time in service-monitoring widget.

Modifications are made for NDO and Centreon Broker.

Regards,

**Comment by CharlesJUDITH** [comment]
My patch was dropped after the migration on github ? Can't see it on this issue, it's a little bit useful if we could see it there.
