### ISSUE TITLE
servicegroup filtre ne fonctionne pas avec des templates

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-service-monitoring#24]
---

Author Name: **Pateretou -** (Pateretou -)
Original Redmine Issue: 6147, https://forge.centreon.com/issues/6147
Original Date: 2015-02-18

---

Hello

il semblerait que le filtre par "servicegroup" ne fonctionne pas.
Dans le screenshot "widget_def.png" on voit que je definis bien un filtre par servicegroup.
Dans le screenshot "servicegroup_def.png" on voit que mon serivcegroup existe bien et qu'il contient des *templates*
Dans le screenshot "Widget_result_KO.png" on voit bien le resultat du filtre de widget qui *n affiche rien du tout*
dans le screenshot "widget_result_ok.png" j'ai supprimé le filtre par servicegroup et on voit bien les services qui apparaissent

Il semblerait que si les services groupe contiennent des templates ceux ci ne sont pas pris en compte par le widget.

D'après une premiere analyse il semblerait que le problème vienne du fichier:

service-monitoring/src/index.php à la ligne 228:

@if (isset($preferences['servicegroup']) && $preferences['servicegroup']) {
    $query = CentreonUtils::conditionBuilder($query,
    " s.service_id IN (SELECT service_service_id
      FROM ".$conf_centreon['db'].".servicegroup_relation
      WHERE servicegroup_sg_id = ".$dbb->escape($preferences['servicegroup'])."
      UNION
      SELECT sgr.service_service_id
      FROM ".$conf_centreon['db'].".servicegroup_relation sgr, ".$conf_centreon['db'].".host_service_relation
      WHERE hsr.hostgroup_hg_id = sgr.hostgroup_hg_id
      AND sgr.servicegroup_sg_id = ".$dbb->escape($preferences['servicegroup']).") ");
}
@

cette requete SQL ne semble pas retourner les services qui dependent d'un template

**Comment by pateretou** [comment]
j'ai l'impression que cette modif a disparu (ou n'a pas ete incorporé) dans la 1.4.0 :)
