### ISSUE TITLE
Bad page load to host detail

### ISSUE THREAD

**Issue by bmareau** [Centreon-Widgets/centreon-widget-service-monitoring#31]
Bonjour,

Dans le widget "service-monitoring" lorsque l'on clic sur un host, on a le message suivant "You are not allowed to reach this page".
La page chargée est http://serveur/centreon/main.php?p=20102... au lieu de http://serveur/centreon/main.php?p=20202...

Cordialement

**Comment by mtoufik** [comment]
commit 38cbfab2a6347ab1afd3807545b87b88ccc94cf7

**Comment by querwin** [comment]
OK
