### ISSUE TITLE
problème d'url image et de balise a

### ISSUE THREAD

**Issue by jben94** [Centreon-Widgets/centreon-widget-service-monitoring#35]
Bonjour,
Il y a un problème "/" autour de la variable "centreon_web_path"  ce qui fait des url incorrectes.
Cordialement.

**Comment by jben94** [comment]
Bonjour,

Il y a toujours un problème sur les liens.

331         } elseif (($key == "h_action_url" || $key == "h_notes_url") && $value) {
332             $value = str_replace("http://", "", $value);
333             $value = urlencode($hostObj->replaceMacroInString($row['hostname'], $value));

Proposition :

331         } elseif (($key == "h_action_url" || $key == "h_notes_url") && $value) {
332             $value = preg_replace("/^http[s]?:\/\//", "", $value);
333             $value = $hostObj->replaceMacroInString($row['hostname'], $value);

**Comment by garnier-quentin** [comment]
I confirm the problem.

**Comment by lpinsivy** [comment]
In version 1.4.2 the code is

        } elseif (($key == "h_action_url" || $key == "h_notes_url") && $value) {
            if (!preg_match("/(^http[s]?)|(^\/\/)/", $value)) {
                $value = '//' . $value;
            }
            $value = CentreonUtils::escapeSecure($hostObj->replaceMacroInString($row['hostname'], $value));
        } elseif (($key == "s_action_url" || $key == "s_notes_url") && $value) {
            if (!preg_match("/(^http[s]?)|(^\/\/)/", $value)) {
                $value = '//' . $value;
            }
            $value = $hostObj->replaceMacroInString($row['hostname'], $value);

Should be already corrected
