### ISSUE TITLE
issues #24 is not solved

### ISSUE THREAD

**Issue by pateretou** [Centreon-Widgets/centreon-widget-service-monitoring#36]
Salut

je ne peux pas "re ouvrir" un bug closed mais il me semble que le bug #24 n'est pas résolu :) (ou surtout qu'il n'a pas ete incorporé au git?)

https://github.com/Centreon-Widgets/centreon-widget-service-monitoring/issues/24

merci!

**Comment by querwin** [comment]
You're right :)
