### ISSUE TITLE
In the widgets of centreon 2.7.2, all the drop-down menu have disappeared

### ISSUE THREAD

**Issue by tseegers** [Centreon-Widgets/centreon-widget-service-monitoring#40]
Hello,

Since the update of Centreon 2.7.2, the drop-down menu of the following widgets have disappeared:

- Host-monitoring (1.4.1-2)
- Service-monitoring (1.4.1-6)

![capture1](https://cloud.githubusercontent.com/assets/13485588/13350984/eb460cac-dc83-11e5-97ff-4f169bae5d36.PNG)

Whereas with widgets host-monitoring-1.4.0-3 & service-monitoring-1.4.0-3, the menu was present:
![capture2](https://cloud.githubusercontent.com/assets/13485588/13351130/dba6b156-dc84-11e5-87c7-a346190dbac9.PNG)

**Comment by julienmathis** [comment]
The drop down menu is now in option. Please check the option checkbox :)

**Comment by tseegers** [comment]
Thank you Julien, you are right, we need to check the box "Enable pagination and more actions" which is disable by default in the option of the widget.
