### ISSUE TITLE
When sharing a view for a contact group : Error message "No layout found for view_id :"

### ISSUE THREAD

**Issue by Jordan91** [Centreon-Widgets/centreon-widget-service-monitoring#44]
When sharing a view for a contact group : Error message "No layout found for view_id :"

![widget 2](https://cloud.githubusercontent.com/assets/16045498/14323614/778aabfc-fc21-11e5-80e6-3bb27d3ead41.png)

**Comment by julienmathis** [comment]
Please open this ticket in centreon/centreon project. This is a centreon problem.

Thanks

**Comment by Jordan91** [comment]
Bonjour,

C'est fait, désolé pour la mauvaise catégorisation.

Bien à toi,

Jordan CARO
Service DESK Centreon

**Comment by julienmathis** [comment]
pas de souci :)

--
Julien  MATHIS

Co-Founder & Chief Technical Officer

Standard: +33 (0) 1 49 69 97 12
Direct: +33(0)1 82 21 80 12
jmathis@centreon.com <jmathis@merethis.com>
[image: Centreon_Logo_RVB_Light_200x76px.png]
*The Power Of Knowing*
Website <http://www.centreon.com/> | Blog <http://blog.centreon.com/>
| Github <https://github.com/centreon/> | Twitter
<https://twitter.com/Centreon>
