### ISSUE TITLE
Hide Checkboxes on each lines if no actions available

### ISSUE THREAD

**Issue by lpinsivy** [Centreon-Widgets/centreon-widget-service-monitoring#45]
From florian-asche

Hi,

if disable:

```
Enable pagination and more actions
```

we dont need the checkboxes. There we can save some space for text.

Origin ticket : https://github.com/centreon/centreon/issues/4297

**Comment by florian-asche** [comment]
Hi, thanks for this change. Can you add this for the other plugins too?

- [ ] servicegroup-monitoring
- [ ] host-monitoring
- [ ] hostgroup-monitoring
