### ISSUE TITLE
Status des services dans la widgets service-monitoring

### ISSUE THREAD

**Issue by bmareau** [Centreon-Widgets/centreon-widget-service-monitoring#52]
Bonjour,

Il serait intéressant d'avoir une option pour changer la couleur de la ligne entière, en fonction du status du service.
Dans le widget 'host-monitoring' lorsque l'hôte passe en Critical, la ligne complète passe en rouge. Dans le même esprit, il serait bien de pouvoir le faire pour le widget service-monitoring.

Cdlt

**Comment by lpinsivy** [comment]
link to #49
